<a href="https://www.kaggle.com/code/ahsanullah002/mlb-2-class-5-assignment?scriptVersionId=347226165" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [157]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [158]:
import numpy as np
import pandas as pd

In [159]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [160]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [161]:
array_1d=np.array([1,2,3])
array_1d

array([1, 2, 3])

In [162]:
array_2d=np.array([[1,2],[3,4]])
array_2d

array([[1, 2],
       [3, 4]])

In [163]:
array_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [164]:
array_4d=np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[8,10],[11,12]],[[13,14],[15,16]]]])
array_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 8, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [165]:
a_1d=np.arange(12)
a_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [166]:
a_2d=np.arange(12).reshape(3,4)
a_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
a_3d=np.arange(16).reshape(2,2,4)
a_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [168]:
a_4d=np.arange(16).reshape(2,2,2,2)
a_4d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# create array using ones and zeros

In [169]:
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [170]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# using random

In [171]:
random=np.random.random([3,3])
random

array([[0.59152384, 0.11607073, 0.65939289],
       [0.51224591, 0.66592444, 0.24509413],
       [0.70202665, 0.29647621, 0.80682075]])

# using linspace

In [172]:
linspace=np.linspace(0,2,5)
linspace

array([0. , 0.5, 1. , 1.5, 2. ])

# create 1D array of tip from tips dataframe

In [173]:
tip_1d=tips['tip'].to_numpy()
tip_1d

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

# create 2D array of tip and total_bill form tips dataframe

In [174]:
bill_2d=tips[['tip','total_bill']].to_numpy()
bill_2d

array([[ 1.01, 16.99],
       [ 1.66, 10.34],
       [ 3.5 , 21.01],
       [ 3.31, 23.68],
       [ 3.61, 24.59],
       [ 4.71, 25.29],
       [ 2.  ,  8.77],
       [ 3.12, 26.88],
       [ 1.96, 15.04],
       [ 3.23, 14.78],
       [ 1.71, 10.27],
       [ 5.  , 35.26],
       [ 1.57, 15.42],
       [ 3.  , 18.43],
       [ 3.02, 14.83],
       [ 3.92, 21.58],
       [ 1.67, 10.33],
       [ 3.71, 16.29],
       [ 3.5 , 16.97],
       [ 3.35, 20.65],
       [ 4.08, 17.92],
       [ 2.75, 20.29],
       [ 2.23, 15.77],
       [ 7.58, 39.42],
       [ 3.18, 19.82],
       [ 2.34, 17.81],
       [ 2.  , 13.37],
       [ 2.  , 12.69],
       [ 4.3 , 21.7 ],
       [ 3.  , 19.65],
       [ 1.45,  9.55],
       [ 2.5 , 18.35],
       [ 3.  , 15.06],
       [ 2.45, 20.69],
       [ 3.27, 17.78],
       [ 3.6 , 24.06],
       [ 2.  , 16.31],
       [ 3.07, 16.93],
       [ 2.31, 18.69],
       [ 5.  , 31.27],
       [ 2.24, 16.04],
       [ 2.54, 17.46],
       [ 3.06, 13.94],
       [ 1.

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [175]:
a1=np.arange(9).reshape(3,3)
b1=np.arange(9,18).reshape(3,3)

In [176]:
a1.ndim

2

In [177]:
bill_2d.ndim

2

In [178]:
a1.shape

(3, 3)

In [179]:
bill_2d.shape

(244, 2)

In [180]:
a1.size

9

In [181]:
bill_2d.size

488

In [182]:
a1.itemsize

8

In [183]:
bill_2d.itemsize

8

# change data type and memory size of any np-array using astype()

In [184]:
a1=a1.astype(np.int32)
a1.itemsize

4

# create 2 same dimensional array and do scalar and vector operations

In [185]:
a1+b1

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [186]:
a1-b1

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [187]:
a1*b1

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [188]:
a1/b1

array([[0.        , 0.1       , 0.18181818],
       [0.25      , 0.30769231, 0.35714286],
       [0.4       , 0.4375    , 0.47058824]])

In [189]:
a1*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]], dtype=int32)

# find minimun and maximum tip

In [190]:
np.min(tip_1d)

np.float64(1.0)

In [191]:
np.max(tip_1d)

np.float64(10.0)

# find average total_bill and average tip

In [192]:
np.mean(tip_1d)

np.float64(2.99827868852459)

# find median total_bill

In [193]:
np.median(tip_1d)

np.float64(2.9)

# find standard deviasion and variance of tip

In [194]:
np.std(tip_1d)

np.float64(1.3807999538298954)

In [195]:
np.var(tip_1d)

np.float64(1.9066085124966412)

# find log values of tip

In [196]:
np.log(tip_1d)

array([0.00995033, 0.5068176 , 1.25276297, 1.19694819, 1.28370777,
       1.54968791, 0.69314718, 1.137833  , 0.67294447, 1.17248214,
       0.53649337, 1.60943791, 0.45107562, 1.09861229, 1.10525683,
       1.36609165, 0.51282363, 1.31103188, 1.25276297, 1.20896035,
       1.40609699, 1.01160091, 0.80200159, 2.0255132 , 1.1568812 ,
       0.85015093, 0.69314718, 0.69314718, 1.45861502, 1.09861229,
       0.37156356, 0.91629073, 1.09861229, 0.89608802, 1.18478998,
       1.28093385, 0.69314718, 1.12167756, 0.83724752, 1.60943791,
       0.80647587, 0.93216408, 1.11841492, 0.27763174, 1.7227666 ,
       1.09861229, 1.60943791, 1.79175947, 0.71783979, 1.09861229,
       0.91629073, 0.95551145, 1.64865863, 0.44468582, 1.46787435,
       1.25561604, 1.09861229, 0.40546511, 0.56531381, 1.90657514,
       1.16627094, 0.69314718, 0.68309684, 1.32441896, 0.97077892,
       1.14740245, 0.90421815, 0.        , 0.69813472, 0.73716407,
       0.67803354, 1.09861229, 1.1442228 , 1.60943791, 0.78845

# apply round, floor and ceil operation on tip array

In [197]:
np.round(tip_1d)

array([ 1.,  2.,  4.,  3.,  4.,  5.,  2.,  3.,  2.,  3.,  2.,  5.,  2.,
        3.,  3.,  4.,  2.,  4.,  4.,  3.,  4.,  3.,  2.,  8.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  4.,  2.,  3.,  2.,
        5.,  2.,  3.,  3.,  1.,  6.,  3.,  5.,  6.,  2.,  3.,  2.,  3.,
        5.,  2.,  4.,  4.,  3.,  2.,  2.,  7.,  3.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  3.,  3.,  3.,  2.,  5.,  2.,  5.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  4.,  3.,  5.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  3.,
        4.,  2.,  4.,  4.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  5.,
        2.,  2.,  3.,  2.,  2.,  2.,  2.,  3.,  4.,  1.,  2.,  2.,  2.,
        2.,  3.,  2.,  2.,  3.,  1.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  2.,  5.,
        5.,  4.,  3.,  2.,  4.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  2.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  4.,  4

In [198]:
np.floor(tip_1d)

array([ 1.,  1.,  3.,  3.,  3.,  4.,  2.,  3.,  1.,  3.,  1.,  5.,  1.,
        3.,  3.,  3.,  1.,  3.,  3.,  3.,  4.,  2.,  2.,  7.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  3.,  2.,  3.,  2.,
        5.,  2.,  2.,  3.,  1.,  5.,  3.,  5.,  6.,  2.,  3.,  2.,  2.,
        5.,  1.,  4.,  3.,  3.,  1.,  1.,  6.,  3.,  2.,  1.,  3.,  2.,
        3.,  2.,  1.,  2.,  2.,  1.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  2.,  3.,  3.,  1.,  5.,  2.,  5.,  2.,  4.,  5.,  3.,  3.,
        3.,  1.,  4.,  3.,  4.,  4.,  1.,  3.,  1.,  2.,  3.,  2.,  3.,
        4.,  1.,  4.,  4.,  3.,  4.,  3.,  1.,  4.,  2.,  4.,  3.,  5.,
        1.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,  4.,  1.,  2.,  2.,  2.,
        1.,  2.,  1.,  2.,  3.,  1.,  2.,  2.,  2.,  2.,  3.,  6.,  5.,
        5.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  5.,
        5.,  3.,  2.,  2.,  3.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  1.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  3.,  3

In [199]:
np.ceil(tip_1d)

array([ 2.,  2.,  4.,  4.,  4.,  5.,  2.,  4.,  2.,  4.,  2.,  5.,  2.,
        3.,  4.,  4.,  2.,  4.,  4.,  4.,  5.,  3.,  3.,  8.,  4.,  3.,
        2.,  2.,  5.,  3.,  2.,  3.,  3.,  3.,  4.,  4.,  2.,  4.,  3.,
        5.,  3.,  3.,  4.,  2.,  6.,  3.,  5.,  6.,  3.,  3.,  3.,  3.,
        6.,  2.,  5.,  4.,  3.,  2.,  2.,  7.,  4.,  2.,  2.,  4.,  3.,
        4.,  3.,  1.,  3.,  3.,  2.,  3.,  4.,  5.,  3.,  2.,  4.,  4.,
        3.,  3.,  3.,  4.,  2.,  5.,  3.,  6.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  5.,  4.,  5.,  4.,  2.,  3.,  2.,  3.,  3.,  3.,  4.,
        5.,  2.,  5.,  5.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  6.,
        2.,  2.,  3.,  3.,  2.,  3.,  2.,  3.,  5.,  2.,  2.,  2.,  3.,
        2.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  3.,  2.,  2.,  6.,
        5.,  4.,  3.,  2.,  4.,  3.,  2.,  2.,  3.,  4.,  3.,  5.,  2.,
        2., 10.,  4.,  6.,  4.,  4.,  4.,  2.,  2.,  4.,  4.,  4

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [200]:
a_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [201]:
a_1d[4:9]

array([4, 5, 6, 7, 8])

In [202]:
a_1d[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [203]:
a_1d[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [204]:
tip_1d[12:17]

array([1.57, 3.  , 3.02, 3.92, 1.67])

In [205]:
b1

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [206]:
b1[1:2,1:2]

array([[13]])

In [207]:
b1[1:,1:]

array([[13, 14],
       [16, 17]])

In [208]:
b1[:1,1:]

array([[10, 11]])

In [209]:
b1[:,1:2]

array([[10],
       [13],
       [16]])

In [210]:
b1[0:2,:]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [211]:
a_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [212]:
a_3d[1,0:,1:]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [213]:
a_3d[1,0:1,1:]

array([[ 9, 10, 11]])

In [214]:
a_3d[1,0:1,1:3]

array([[ 9, 10]])

In [215]:
a_3d[:,0:1,1:3]

array([[[ 1,  2]],

       [[ 9, 10]]])

In [216]:
a_3d[:,0:,2:3]

array([[[ 2],
        [ 6]],

       [[10],
        [14]]])

# stacking and spliting

In [217]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

In [218]:
np.hstack([d,e])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8, 28, 29, 30, 31, 32, 33, 34,
        35, 36],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 37, 38, 39, 40, 41, 42, 43,
        44, 45],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 46, 47, 48, 49, 50, 51, 52,
        53, 54]])

In [219]:
np.vstack([d,e])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

# use hsplit() and vsplit()

In [220]:
np.hsplit(d,3)

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]])]

In [221]:
np.vsplit(d,3)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]